"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.role_update_role_request_body import RoleUpdateRoleRequestBody


class TestRoleUpdateRoleRequestBody(unittest.TestCase):
    """RoleUpdateRoleRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleUpdateRoleRequestBody(self):
        """Test RoleUpdateRoleRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleUpdateRoleRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
