"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cwe_response_body import CweResponseBody


class TestCweResponseBody(unittest.TestCase):
    """CweResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCweResponseBody(self):
        """Test CweResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CweResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
