"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.advisory_response_body import AdvisoryResponseBody
from openapi_client.model.cwe_response_body import CweResponseBody
from openapi_client.model.env_metric_v2_response_body import EnvMetricV2ResponseBody
from openapi_client.model.env_metric_v3_response_body import EnvMetricV3ResponseBody
from openapi_client.model.sec_metric_response_body import SecMetricResponseBody
from openapi_client.model.tmp_metric_response_body import TmpMetricResponseBody
globals()['AdvisoryResponseBody'] = AdvisoryResponseBody
globals()['CweResponseBody'] = CweResponseBody
globals()['EnvMetricV2ResponseBody'] = EnvMetricV2ResponseBody
globals()['EnvMetricV3ResponseBody'] = EnvMetricV3ResponseBody
globals()['SecMetricResponseBody'] = SecMetricResponseBody
globals()['TmpMetricResponseBody'] = TmpMetricResponseBody
from openapi_client.model.cve_get_cve_detail_response_body import CveGetCveDetailResponseBody


class TestCveGetCveDetailResponseBody(unittest.TestCase):
    """CveGetCveDetailResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveGetCveDetailResponseBody(self):
        """Test CveGetCveDetailResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveGetCveDetailResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
