"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.affected_proc_response_body import AffectedProcResponseBody
globals()['AffectedProcResponseBody'] = AffectedProcResponseBody
from openapi_client.model.pkg_cpe_child_response_body import PkgCpeChildResponseBody


class TestPkgCpeChildResponseBody(unittest.TestCase):
    """PkgCpeChildResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeChildResponseBody(self):
        """Test PkgCpeChildResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeChildResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
