"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.env_metric_v2_response_body import EnvMetricV2ResponseBody
from openapi_client.model.env_metric_v3_response_body import EnvMetricV3ResponseBody
from openapi_client.model.sec_metric_response_body import SecMetricResponseBody
from openapi_client.model.server_child_response_body import ServerChildResponseBody
globals()['EnvMetricV2ResponseBody'] = EnvMetricV2ResponseBody
globals()['EnvMetricV3ResponseBody'] = EnvMetricV3ResponseBody
globals()['SecMetricResponseBody'] = SecMetricResponseBody
globals()['ServerChildResponseBody'] = ServerChildResponseBody
from openapi_client.model.role_update_role_response_body import RoleUpdateRoleResponseBody


class TestRoleUpdateRoleResponseBody(unittest.TestCase):
    """RoleUpdateRoleResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleUpdateRoleResponseBody(self):
        """Test RoleUpdateRoleResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleUpdateRoleResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
