"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.paging_response_body import PagingResponseBody
from openapi_client.model.role_list_response_body import RoleListResponseBody
globals()['PagingResponseBody'] = PagingResponseBody
globals()['RoleListResponseBody'] = RoleListResponseBody
from openapi_client.model.role_get_role_list_response_body import RoleGetRoleListResponseBody


class TestRoleGetRoleListResponseBody(unittest.TestCase):
    """RoleGetRoleListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleGetRoleListResponseBody(self):
        """Test RoleGetRoleListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoleGetRoleListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
