"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.paging_response_body import PagingResponseBody
from openapi_client.model.pkg_cpe_list_response_body import PkgCpeListResponseBody
globals()['PagingResponseBody'] = PagingResponseBody
globals()['PkgCpeListResponseBody'] = PkgCpeListResponseBody
from openapi_client.model.pkg_cpe_get_pkg_cpe_list_response_body import PkgCpeGetPkgCpeListResponseBody


class TestPkgCpeGetPkgCpeListResponseBody(unittest.TestCase):
    """PkgCpeGetPkgCpeListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeGetPkgCpeListResponseBody(self):
        """Test PkgCpeGetPkgCpeListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeGetPkgCpeListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
