"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.detection_method_response_body import DetectionMethodResponseBody
from openapi_client.model.detection_tool_response_body import DetectionToolResponseBody
from openapi_client.model.pkg_cpe_child_response_body import PkgCpeChildResponseBody
from openapi_client.model.server_child_response_body import ServerChildResponseBody
from openapi_client.model.task_comment_response_body import TaskCommentResponseBody
globals()['DetectionMethodResponseBody'] = DetectionMethodResponseBody
globals()['DetectionToolResponseBody'] = DetectionToolResponseBody
globals()['PkgCpeChildResponseBody'] = PkgCpeChildResponseBody
globals()['ServerChildResponseBody'] = ServerChildResponseBody
globals()['TaskCommentResponseBody'] = TaskCommentResponseBody
from openapi_client.model.task_update_task_ignore_response_body import TaskUpdateTaskIgnoreResponseBody


class TestTaskUpdateTaskIgnoreResponseBody(unittest.TestCase):
    """TaskUpdateTaskIgnoreResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskUpdateTaskIgnoreResponseBody(self):
        """Test TaskUpdateTaskIgnoreResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskUpdateTaskIgnoreResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
