"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.task_update_task_ignore_request_body import TaskUpdateTaskIgnoreRequestBody


class TestTaskUpdateTaskIgnoreRequestBody(unittest.TestCase):
    """TaskUpdateTaskIgnoreRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskUpdateTaskIgnoreRequestBody(self):
        """Test TaskUpdateTaskIgnoreRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskUpdateTaskIgnoreRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
