"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.lockfile_list_response_body import LockfileListResponseBody
from openapi_client.model.paging_response_body import PagingResponseBody
globals()['LockfileListResponseBody'] = LockfileListResponseBody
globals()['PagingResponseBody'] = PagingResponseBody
from openapi_client.model.lockfile_get_lockfile_list_response_body import LockfileGetLockfileListResponseBody


class TestLockfileGetLockfileListResponseBody(unittest.TestCase):
    """LockfileGetLockfileListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLockfileGetLockfileListResponseBody(self):
        """Test LockfileGetLockfileListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LockfileGetLockfileListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
