"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pkg_cpe_delete_cpe_deprecated_request_body import PkgCpeDeleteCpeDeprecatedRequestBody


class TestPkgCpeDeleteCpeDeprecatedRequestBody(unittest.TestCase):
    """PkgCpeDeleteCpeDeprecatedRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeDeleteCpeDeprecatedRequestBody(self):
        """Test PkgCpeDeleteCpeDeprecatedRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeDeleteCpeDeprecatedRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
