"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.tmp_metric_response_body import TmpMetricResponseBody


class TestTmpMetricResponseBody(unittest.TestCase):
    """TmpMetricResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTmpMetricResponseBody(self):
        """Test TmpMetricResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TmpMetricResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
