"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sec_metric_response_body import SecMetricResponseBody


class TestSecMetricResponseBody(unittest.TestCase):
    """SecMetricResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecMetricResponseBody(self):
        """Test SecMetricResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecMetricResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
