"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.role_api import RoleApi  # noqa: E501


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_role_delete_role(self):
        """Test case for role_delete_role

        deleteRole role  # noqa: E501
        """
        pass

    def test_role_get_role_detail(self):
        """Test case for role_get_role_detail

        getRoleDetail role  # noqa: E501
        """
        pass

    def test_role_get_role_list(self):
        """Test case for role_get_role_list

        getRoleList role  # noqa: E501
        """
        pass

    def test_role_update_role(self):
        """Test case for role_update_role

        updateRole role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
