"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.child_task_response_body import ChildTaskResponseBody
from openapi_client.model.server_tag_response_body import ServerTagResponseBody
globals()['ChildTaskResponseBody'] = ChildTaskResponseBody
globals()['ServerTagResponseBody'] = ServerTagResponseBody
from openapi_client.model.server_create_pkg_paste_server_response_body import ServerCreatePkgPasteServerResponseBody


class TestServerCreatePkgPasteServerResponseBody(unittest.TestCase):
    """ServerCreatePkgPasteServerResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerCreatePkgPasteServerResponseBody(self):
        """Test ServerCreatePkgPasteServerResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerCreatePkgPasteServerResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
