"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_update_server_request_body import ServerUpdateServerRequestBody


class TestServerUpdateServerRequestBody(unittest.TestCase):
    """ServerUpdateServerRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerUpdateServerRequestBody(self):
        """Test ServerUpdateServerRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerUpdateServerRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
