"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cve_list_response_body import CveListResponseBody
from openapi_client.model.paging_response_body import PagingResponseBody
globals()['CveListResponseBody'] = CveListResponseBody
globals()['PagingResponseBody'] = PagingResponseBody
from openapi_client.model.cve_get_cve_list_response_body import CveGetCveListResponseBody


class TestCveGetCveListResponseBody(unittest.TestCase):
    """CveGetCveListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveGetCveListResponseBody(self):
        """Test CveGetCveListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveGetCveListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
