"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.paging_response_body import PagingResponseBody


class TestPagingResponseBody(unittest.TestCase):
    """PagingResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPagingResponseBody(self):
        """Test PagingResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PagingResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
