"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.library_pkg_child_response_body import LibraryPkgChildResponseBody
from openapi_client.model.server_child_response_body import ServerChildResponseBody
globals()['LibraryPkgChildResponseBody'] = LibraryPkgChildResponseBody
globals()['ServerChildResponseBody'] = ServerChildResponseBody
from openapi_client.model.lockfile_update_lockfile_response_body import LockfileUpdateLockfileResponseBody


class TestLockfileUpdateLockfileResponseBody(unittest.TestCase):
    """LockfileUpdateLockfileResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLockfileUpdateLockfileResponseBody(self):
        """Test LockfileUpdateLockfileResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LockfileUpdateLockfileResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
