"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pkg_cpe_add_cpe_request_body import PkgCpeAddCpeRequestBody


class TestPkgCpeAddCpeRequestBody(unittest.TestCase):
    """PkgCpeAddCpeRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeAddCpeRequestBody(self):
        """Test PkgCpeAddCpeRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeAddCpeRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
