"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.env_metric_v3_response_body import EnvMetricV3ResponseBody


class TestEnvMetricV3ResponseBody(unittest.TestCase):
    """EnvMetricV3ResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnvMetricV3ResponseBody(self):
        """Test EnvMetricV3ResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnvMetricV3ResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
