"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.need_restart_proc_response_body import NeedRestartProcResponseBody


class TestNeedRestartProcResponseBody(unittest.TestCase):
    """NeedRestartProcResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNeedRestartProcResponseBody(self):
        """Test NeedRestartProcResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NeedRestartProcResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
