"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.lockfile_add_lockfile_request_body import LockfileAddLockfileRequestBody


class TestLockfileAddLockfileRequestBody(unittest.TestCase):
    """LockfileAddLockfileRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLockfileAddLockfileRequestBody(self):
        """Test LockfileAddLockfileRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LockfileAddLockfileRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
