"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.task_add_task_comment_request_body import TaskAddTaskCommentRequestBody


class TestTaskAddTaskCommentRequestBody(unittest.TestCase):
    """TaskAddTaskCommentRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskAddTaskCommentRequestBody(self):
        """Test TaskAddTaskCommentRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskAddTaskCommentRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
