"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.pkg_cpe_api import PkgCpeApi  # noqa: E501


class TestPkgCpeApi(unittest.TestCase):
    """PkgCpeApi unit test stubs"""

    def setUp(self):
        self.api = PkgCpeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pkg_cpe_add_cpe(self):
        """Test case for pkg_cpe_add_cpe

        addCpe pkgCpe  # noqa: E501
        """
        pass

    def test_pkg_cpe_delete_cpe(self):
        """Test case for pkg_cpe_delete_cpe

        deleteCpe pkgCpe  # noqa: E501
        """
        pass

    def test_pkg_cpe_delete_cpe_deprecated(self):
        """Test case for pkg_cpe_delete_cpe_deprecated

        deleteCpe_deprecated pkgCpe  # noqa: E501
        """
        pass

    def test_pkg_cpe_get_cpe_detail(self):
        """Test case for pkg_cpe_get_cpe_detail

        getCpeDetail pkgCpe  # noqa: E501
        """
        pass

    def test_pkg_cpe_get_pkg_cpe_list(self):
        """Test case for pkg_cpe_get_pkg_cpe_list

        getPkgCpeList pkgCpe  # noqa: E501
        """
        pass

    def test_pkg_cpe_get_pkg_detail(self):
        """Test case for pkg_cpe_get_pkg_detail

        getPkgDetail pkgCpe  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
