"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.child_task_response_body import ChildTaskResponseBody
from openapi_client.model.server_child_response_body import ServerChildResponseBody
globals()['ChildTaskResponseBody'] = ChildTaskResponseBody
globals()['ServerChildResponseBody'] = ServerChildResponseBody
from openapi_client.model.pkg_cpe_get_cpe_detail_response_body import PkgCpeGetCpeDetailResponseBody


class TestPkgCpeGetCpeDetailResponseBody(unittest.TestCase):
    """PkgCpeGetCpeDetailResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeGetCpeDetailResponseBody(self):
        """Test PkgCpeGetCpeDetailResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeGetCpeDetailResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
