"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.paging_response_body import PagingResponseBody
from openapi_client.model.server_list_response_body import ServerListResponseBody
globals()['PagingResponseBody'] = PagingResponseBody
globals()['ServerListResponseBody'] = ServerListResponseBody
from openapi_client.model.server_get_server_list_response_body import ServerGetServerListResponseBody


class TestServerGetServerListResponseBody(unittest.TestCase):
    """ServerGetServerListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerGetServerListResponseBody(self):
        """Test ServerGetServerListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerGetServerListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
