"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.advisory_response_body import AdvisoryResponseBody


class TestAdvisoryResponseBody(unittest.TestCase):
    """AdvisoryResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdvisoryResponseBody(self):
        """Test AdvisoryResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AdvisoryResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
