"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.paging_response_body import PagingResponseBody
from openapi_client.model.task_list_response_body import TaskListResponseBody
globals()['PagingResponseBody'] = PagingResponseBody
globals()['TaskListResponseBody'] = TaskListResponseBody
from openapi_client.model.task_get_task_list_response_body import TaskGetTaskListResponseBody


class TestTaskGetTaskListResponseBody(unittest.TestCase):
    """TaskGetTaskListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskGetTaskListResponseBody(self):
        """Test TaskGetTaskListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TaskGetTaskListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
