"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_tag_response_body import ServerTagResponseBody
globals()['ServerTagResponseBody'] = ServerTagResponseBody
from openapi_client.model.server_list_response_body import ServerListResponseBody


class TestServerListResponseBody(unittest.TestCase):
    """ServerListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerListResponseBody(self):
        """Test ServerListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
