"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.affected_proc_response_body import AffectedProcResponseBody
from openapi_client.model.child_task_response_body import ChildTaskResponseBody
from openapi_client.model.need_restart_proc_response_body import NeedRestartProcResponseBody
from openapi_client.model.server_child_response_body import ServerChildResponseBody
globals()['AffectedProcResponseBody'] = AffectedProcResponseBody
globals()['ChildTaskResponseBody'] = ChildTaskResponseBody
globals()['NeedRestartProcResponseBody'] = NeedRestartProcResponseBody
globals()['ServerChildResponseBody'] = ServerChildResponseBody
from openapi_client.model.pkg_cpe_get_pkg_detail_response_body import PkgCpeGetPkgDetailResponseBody


class TestPkgCpeGetPkgDetailResponseBody(unittest.TestCase):
    """PkgCpeGetPkgDetailResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeGetPkgDetailResponseBody(self):
        """Test PkgCpeGetPkgDetailResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeGetPkgDetailResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
