"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.need_restart_proc_response_body import NeedRestartProcResponseBody
globals()['NeedRestartProcResponseBody'] = NeedRestartProcResponseBody
from openapi_client.model.pkg_cpe_list_response_body import PkgCpeListResponseBody


class TestPkgCpeListResponseBody(unittest.TestCase):
    """PkgCpeListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPkgCpeListResponseBody(self):
        """Test PkgCpeListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PkgCpeListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
