"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.task_api import TaskApi  # noqa: E501


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self):
        self.api = TaskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_task_add_task_comment(self):
        """Test case for task_add_task_comment

        addTaskComment task  # noqa: E501
        """
        pass

    def test_task_get_task_detail(self):
        """Test case for task_get_task_detail

        getTaskDetail task  # noqa: E501
        """
        pass

    def test_task_get_task_list(self):
        """Test case for task_get_task_list

        getTaskList task  # noqa: E501
        """
        pass

    def test_task_update_task(self):
        """Test case for task_update_task

        updateTask task  # noqa: E501
        """
        pass

    def test_task_update_task_ignore(self):
        """Test case for task_update_task_ignore

        updateTaskIgnore task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
