"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_update_pkg_paste_server_request_body import ServerUpdatePkgPasteServerRequestBody


class TestServerUpdatePkgPasteServerRequestBody(unittest.TestCase):
    """ServerUpdatePkgPasteServerRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerUpdatePkgPasteServerRequestBody(self):
        """Test ServerUpdatePkgPasteServerRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerUpdatePkgPasteServerRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
