"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.library_pkg_child_response_body import LibraryPkgChildResponseBody


class TestLibraryPkgChildResponseBody(unittest.TestCase):
    """LibraryPkgChildResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibraryPkgChildResponseBody(self):
        """Test LibraryPkgChildResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LibraryPkgChildResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
