"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.cwe_response_body import CweResponseBody
globals()['CweResponseBody'] = CweResponseBody
from openapi_client.model.cve_list_response_body import CveListResponseBody


class TestCveListResponseBody(unittest.TestCase):
    """CveListResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCveListResponseBody(self):
        """Test CveListResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CveListResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
