"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.need_restart_proc_response_body import NeedRestartProcResponseBody
    globals()['NeedRestartProcResponseBody'] = NeedRestartProcResponseBody


class PkgCpeListResponseBody(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'created_at': (datetime,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'server_id': (int,),  # noqa: E501
            'server_name': (str,),  # noqa: E501
            'server_uuid': (str,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'version': (str,),  # noqa: E501
            'application_name': (str,),  # noqa: E501
            'cpe_fs': (str,),  # noqa: E501
            'cpe_id': (int,),  # noqa: E501
            'cpe_uri': (str,),  # noqa: E501
            'github_pkg_id': (int,),  # noqa: E501
            'library_path': (str,),  # noqa: E501
            'library_pkg_id': (int,),  # noqa: E501
            'need_restart_procs': ([NeedRestartProcResponseBody],),  # noqa: E501
            'new_release': (str,),  # noqa: E501
            'new_version': (str,),  # noqa: E501
            'not_fixed_yet': (bool,),  # noqa: E501
            'oss_license': (str,),  # noqa: E501
            'pkg_id': (int,),  # noqa: E501
            'release': (str,),  # noqa: E501
            'repository': (str,),  # noqa: E501
            'wordpress_package_status': (str,),  # noqa: E501
            'wordpress_pkg_id': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'created_at': 'createdAt',  # noqa: E501
        'name': 'name',  # noqa: E501
        'server_id': 'serverID',  # noqa: E501
        'server_name': 'serverName',  # noqa: E501
        'server_uuid': 'serverUuid',  # noqa: E501
        'updated_at': 'updatedAt',  # noqa: E501
        'version': 'version',  # noqa: E501
        'application_name': 'applicationName',  # noqa: E501
        'cpe_fs': 'cpeFS',  # noqa: E501
        'cpe_id': 'cpeID',  # noqa: E501
        'cpe_uri': 'cpeURI',  # noqa: E501
        'github_pkg_id': 'githubPkgID',  # noqa: E501
        'library_path': 'libraryPath',  # noqa: E501
        'library_pkg_id': 'libraryPkgID',  # noqa: E501
        'need_restart_procs': 'needRestartProcs',  # noqa: E501
        'new_release': 'newRelease',  # noqa: E501
        'new_version': 'newVersion',  # noqa: E501
        'not_fixed_yet': 'notFixedYet',  # noqa: E501
        'oss_license': 'ossLicense',  # noqa: E501
        'pkg_id': 'pkgID',  # noqa: E501
        'release': 'release',  # noqa: E501
        'repository': 'repository',  # noqa: E501
        'wordpress_package_status': 'wordpressPackageStatus',  # noqa: E501
        'wordpress_pkg_id': 'wordpressPkgID',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, created_at, name, server_id, server_name, server_uuid, updated_at, version, *args, **kwargs):  # noqa: E501
        """PkgCpeListResponseBody - a model defined in OpenAPI

        Args:
            created_at (datetime): crated time of package or cpe
            name (str): Name of package or cpe
            server_id (int): ServerID of package or cpe
            server_name (str): ServerName of package or cpe
            server_uuid (str): ServerUUID of package or cpe
            updated_at (datetime): updated time of package or cpe
            version (str): Version of package or cpe

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            application_name (str): ApplicationName of library package. [optional]  # noqa: E501
            cpe_fs (str): Cpe FS of cpe. [optional]  # noqa: E501
            cpe_id (int): CpeID of cpe. [optional]  # noqa: E501
            cpe_uri (str): Cpe URI of cpe. [optional]  # noqa: E501
            github_pkg_id (int): githubPKGID of github pkg. [optional]  # noqa: E501
            library_path (str): LibraryPath of library package. [optional]  # noqa: E501
            library_pkg_id (int): libraryPKGID of library pkg. [optional]  # noqa: E501
            need_restart_procs ([NeedRestartProcResponseBody]): NeedRestartProcess list of package. [optional]  # noqa: E501
            new_release (str): New Release of package. [optional]  # noqa: E501
            new_version (str): New Version of package. [optional]  # noqa: E501
            not_fixed_yet (bool): Flag of Not fixed yet of package. [optional]  # noqa: E501
            oss_license (str): ossLicense of library package. [optional]  # noqa: E501
            pkg_id (int): Package ID of package. [optional]  # noqa: E501
            release (str): Release of package. [optional]  # noqa: E501
            repository (str): Repository of package. [optional]  # noqa: E501
            wordpress_package_status (str): WordpressPackageStatus of wordpress package. [optional]  # noqa: E501
            wordpress_pkg_id (int): wordpressPKGID of wordpress pkg. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.created_at = created_at
        self.name = name
        self.server_id = server_id
        self.server_name = server_name
        self.server_uuid = server_uuid
        self.updated_at = updated_at
        self.version = version
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, created_at, name, server_id, server_name, server_uuid, updated_at, version, *args, **kwargs):  # noqa: E501
        """PkgCpeListResponseBody - a model defined in OpenAPI

        Args:
            created_at (datetime): crated time of package or cpe
            name (str): Name of package or cpe
            server_id (int): ServerID of package or cpe
            server_name (str): ServerName of package or cpe
            server_uuid (str): ServerUUID of package or cpe
            updated_at (datetime): updated time of package or cpe
            version (str): Version of package or cpe

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            application_name (str): ApplicationName of library package. [optional]  # noqa: E501
            cpe_fs (str): Cpe FS of cpe. [optional]  # noqa: E501
            cpe_id (int): CpeID of cpe. [optional]  # noqa: E501
            cpe_uri (str): Cpe URI of cpe. [optional]  # noqa: E501
            github_pkg_id (int): githubPKGID of github pkg. [optional]  # noqa: E501
            library_path (str): LibraryPath of library package. [optional]  # noqa: E501
            library_pkg_id (int): libraryPKGID of library pkg. [optional]  # noqa: E501
            need_restart_procs ([NeedRestartProcResponseBody]): NeedRestartProcess list of package. [optional]  # noqa: E501
            new_release (str): New Release of package. [optional]  # noqa: E501
            new_version (str): New Version of package. [optional]  # noqa: E501
            not_fixed_yet (bool): Flag of Not fixed yet of package. [optional]  # noqa: E501
            oss_license (str): ossLicense of library package. [optional]  # noqa: E501
            pkg_id (int): Package ID of package. [optional]  # noqa: E501
            release (str): Release of package. [optional]  # noqa: E501
            repository (str): Repository of package. [optional]  # noqa: E501
            wordpress_package_status (str): WordpressPackageStatus of wordpress package. [optional]  # noqa: E501
            wordpress_pkg_id (int): wordpressPKGID of wordpress pkg. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.created_at = created_at
        self.name = name
        self.server_id = server_id
        self.server_name = server_name
        self.server_uuid = server_uuid
        self.updated_at = updated_at
        self.version = version
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
