"""
    Future Vuls Public API

    Future Vuls Public API  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.detection_tool_response_body import DetectionToolResponseBody
    globals()['DetectionToolResponseBody'] = DetectionToolResponseBody


class TaskListResponseBody(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'created_at': (datetime,),  # noqa: E501
            'cve_id': (str,),  # noqa: E501
            'id': (int,),  # noqa: E501
            'ignore': (bool,),  # noqa: E501
            'os_family': (str,),  # noqa: E501
            'os_version': (str,),  # noqa: E501
            'priority': (str,),  # noqa: E501
            'role_id': (int,),  # noqa: E501
            'role_name': (str,),  # noqa: E501
            'server_id': (int,),  # noqa: E501
            'server_name': (str,),  # noqa: E501
            'server_uuid': (str,),  # noqa: E501
            'status': (str,),  # noqa: E501
            'updated_at': (datetime,),  # noqa: E501
            'advisory_ids': ([str],),  # noqa: E501
            'applying_patch_on': (date,),  # noqa: E501
            'detection_tools': ([DetectionToolResponseBody],),  # noqa: E501
            'has_exploit': (bool,),  # noqa: E501
            'has_mitigation': (bool,),  # noqa: E501
            'has_workaround': (bool,),  # noqa: E501
            'ignore_until': (str,),  # noqa: E501
            'main_user_id': (int,),  # noqa: E501
            'main_user_name': (str,),  # noqa: E501
            'pkg_cpe_names': ([str],),  # noqa: E501
            'pkg_not_fixed_yet': (bool,),  # noqa: E501
            'server_tags': ([str],),  # noqa: E501
            'sub_user_id': (int,),  # noqa: E501
            'sub_user_name': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'created_at': 'createdAt',  # noqa: E501
        'cve_id': 'cveID',  # noqa: E501
        'id': 'id',  # noqa: E501
        'ignore': 'ignore',  # noqa: E501
        'os_family': 'osFamily',  # noqa: E501
        'os_version': 'osVersion',  # noqa: E501
        'priority': 'priority',  # noqa: E501
        'role_id': 'roleID',  # noqa: E501
        'role_name': 'roleName',  # noqa: E501
        'server_id': 'serverID',  # noqa: E501
        'server_name': 'serverName',  # noqa: E501
        'server_uuid': 'serverUuid',  # noqa: E501
        'status': 'status',  # noqa: E501
        'updated_at': 'updatedAt',  # noqa: E501
        'advisory_ids': 'advisoryIDs',  # noqa: E501
        'applying_patch_on': 'applyingPatchOn',  # noqa: E501
        'detection_tools': 'detectionTools',  # noqa: E501
        'has_exploit': 'hasExploit',  # noqa: E501
        'has_mitigation': 'hasMitigation',  # noqa: E501
        'has_workaround': 'hasWorkaround',  # noqa: E501
        'ignore_until': 'ignoreUntil',  # noqa: E501
        'main_user_id': 'mainUserID',  # noqa: E501
        'main_user_name': 'mainUserName',  # noqa: E501
        'pkg_cpe_names': 'pkgCpeNames',  # noqa: E501
        'pkg_not_fixed_yet': 'pkgNotFixedYet',  # noqa: E501
        'server_tags': 'serverTags',  # noqa: E501
        'sub_user_id': 'subUserID',  # noqa: E501
        'sub_user_name': 'subUserName',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, created_at, cve_id, id, ignore, os_family, os_version, priority, role_id, role_name, server_id, server_name, server_uuid, status, updated_at, *args, **kwargs):  # noqa: E501
        """TaskListResponseBody - a model defined in OpenAPI

        Args:
            created_at (datetime): created time of task
            cve_id (str): CVE ID of task
            id (int): ID of task
            ignore (bool): Ignore of task
            os_family (str): OS Name of server
            os_version (str): OS Version of server
            priority (str): Priority of task
            role_id (int): ServerRoleID of task
            role_name (str): ServerRoleName of task
            server_id (int): ServerID of task
            server_name (str): ServerName of task
            server_uuid (str): ServerUUID of task
            status (str): Status of task
            updated_at (datetime): updated time of task

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            advisory_ids ([str]): advisoryIDs of cve. [optional]  # noqa: E501
            applying_patch_on (date): ApplyingPatchOn of task. [optional]  # noqa: E501
            detection_tools ([DetectionToolResponseBody]): DetectionTools of task. [optional]  # noqa: E501
            has_exploit (bool): hasExploit of cve. [optional]  # noqa: E501
            has_mitigation (bool): hasMitigation of cve. [optional]  # noqa: E501
            has_workaround (bool): hasWorkaroundof cve. [optional]  # noqa: E501
            ignore_until (str): Ignore until of task. [optional]  # noqa: E501
            main_user_id (int): MainUserID of task. [optional]  # noqa: E501
            main_user_name (str): MainUserName of task. [optional]  # noqa: E501
            pkg_cpe_names ([str]): Package And CPE Names of task. [optional]  # noqa: E501
            pkg_not_fixed_yet (bool): Flag of Not Fixed Yet of task. [optional]  # noqa: E501
            server_tags ([str]): ServerTags of task. [optional]  # noqa: E501
            sub_user_id (int): SubUserID of task. [optional]  # noqa: E501
            sub_user_name (str): SubUserName of task. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.created_at = created_at
        self.cve_id = cve_id
        self.id = id
        self.ignore = ignore
        self.os_family = os_family
        self.os_version = os_version
        self.priority = priority
        self.role_id = role_id
        self.role_name = role_name
        self.server_id = server_id
        self.server_name = server_name
        self.server_uuid = server_uuid
        self.status = status
        self.updated_at = updated_at
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, created_at, cve_id, id, ignore, os_family, os_version, priority, role_id, role_name, server_id, server_name, server_uuid, status, updated_at, *args, **kwargs):  # noqa: E501
        """TaskListResponseBody - a model defined in OpenAPI

        Args:
            created_at (datetime): created time of task
            cve_id (str): CVE ID of task
            id (int): ID of task
            ignore (bool): Ignore of task
            os_family (str): OS Name of server
            os_version (str): OS Version of server
            priority (str): Priority of task
            role_id (int): ServerRoleID of task
            role_name (str): ServerRoleName of task
            server_id (int): ServerID of task
            server_name (str): ServerName of task
            server_uuid (str): ServerUUID of task
            status (str): Status of task
            updated_at (datetime): updated time of task

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            advisory_ids ([str]): advisoryIDs of cve. [optional]  # noqa: E501
            applying_patch_on (date): ApplyingPatchOn of task. [optional]  # noqa: E501
            detection_tools ([DetectionToolResponseBody]): DetectionTools of task. [optional]  # noqa: E501
            has_exploit (bool): hasExploit of cve. [optional]  # noqa: E501
            has_mitigation (bool): hasMitigation of cve. [optional]  # noqa: E501
            has_workaround (bool): hasWorkaroundof cve. [optional]  # noqa: E501
            ignore_until (str): Ignore until of task. [optional]  # noqa: E501
            main_user_id (int): MainUserID of task. [optional]  # noqa: E501
            main_user_name (str): MainUserName of task. [optional]  # noqa: E501
            pkg_cpe_names ([str]): Package And CPE Names of task. [optional]  # noqa: E501
            pkg_not_fixed_yet (bool): Flag of Not Fixed Yet of task. [optional]  # noqa: E501
            server_tags ([str]): ServerTags of task. [optional]  # noqa: E501
            sub_user_id (int): SubUserID of task. [optional]  # noqa: E501
            sub_user_name (str): SubUserName of task. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.created_at = created_at
        self.cve_id = cve_id
        self.id = id
        self.ignore = ignore
        self.os_family = os_family
        self.os_version = os_version
        self.priority = priority
        self.role_id = role_id
        self.role_name = role_name
        self.server_id = server_id
        self.server_name = server_name
        self.server_uuid = server_uuid
        self.status = status
        self.updated_at = updated_at
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
